### PR TITLE
deleted unncessary colons

### PR DESCRIPTION
**Pull request by adamjchai**
colons on top of docker.py that were unnecessary I deleted them

### CODE REVIEW

**Review by reillymarkowitz — APPROVED** [review]

**Review by laszewsk — CHANGES_REQUESTED** [review]
the colons are needed

**Comment by reillymarkowitz** [comment]
Thanks Gregor, we won't merge this request.

**Comment by laszewsk** [comment]
The colons are needed thus the pull request is rejected

**Comment by reillymarkowitz** [comment]
For future reference, what are the colons needed for?

**Comment by laszewsk** [comment]
They are needed for generating the man pages for the Web

**Pull request closed without merging**
